/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 14.1 		*/
/*  Created On : 16-may.-2019 2:10:20 				*/
/*  DBMS       : MySql 						*/
/* ---------------------------------------------------- */

SET FOREIGN_KEY_CHECKS=0
; 
/* Drop Tables */

DROP TABLE IF EXISTS `Department` CASCADE
;

DROP TABLE IF EXISTS `Post` CASCADE
;

DROP TABLE IF EXISTS `Professor` CASCADE
;

DROP TABLE IF EXISTS `Professor-Subject` CASCADE
;

DROP TABLE IF EXISTS `Subject` CASCADE
;

DROP TABLE IF EXISTS `User` CASCADE
;

/* Create Tables */

CREATE TABLE `Department`
(
	`idDept` INT NOT NULL AUTO_INCREMENT,
	`departmentName` VARCHAR(20) NOT NULL,
	CONSTRAINT `PK_Department` PRIMARY KEY (`idDept` ASC)
)

;

CREATE TABLE `Post`
(
	`idPost` INT NOT NULL AUTO_INCREMENT,
    `title` VARCHAR(50) NOT NULL,
	`date` date NOT NULL,
	`idSubject` INT NOT NULL,
	`file` BLOB NOT NULL,
	`solution` BLOB NULL,
	`user` VARCHAR(50) NULL,
	CONSTRAINT `PK_Post` PRIMARY KEY (`idPost` ASC)
)

;

CREATE TABLE `Professor`
(
	`idProfessor` INT NOT NULL AUTO_INCREMENT,
	`professorName` VARCHAR(50) NOT NULL,
	CONSTRAINT `PK_Professor` PRIMARY KEY (`idProfessor` ASC)
)

;

CREATE TABLE `Professor-Subject`
(
	`idSubject` INT NOT NULL,
	`idProfessor` INT NOT NULL,
	CONSTRAINT `PK_Professor-Subject` PRIMARY KEY (`idSubject` ASC, `idProfessor` ASC)
)

;

CREATE TABLE `Subject`
(
	`idSubject` INT NOT NULL AUTO_INCREMENT,
	`subjectName` VARCHAR(40) NOT NULL,
	`idDept` INT NOT NULL,
	CONSTRAINT `PK_Subject` PRIMARY KEY (`idSubject` ASC)
)

;

CREATE TABLE `User`
(
	`user` VARCHAR(50) NOT NULL,
	`userName` VARCHAR(50) NOT NULL,
	`email` VARCHAR(40) NOT NULL,
	`password` VARCHAR(36) NOT NULL,
	CONSTRAINT `PK_User` PRIMARY KEY (`user` ASC)
)

;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE `Post` 
 ADD INDEX `IXFK_Post_Subject` (`idSubject` ASC)
;

ALTER TABLE `Post` 
 ADD INDEX `IXFK_Post_User` (`user` ASC)
;

ALTER TABLE `Professor` 
 ADD INDEX `IXFK_Professor_Professor-Subject` (`idProfessor` ASC)
;

ALTER TABLE `Professor-Subject` 
 ADD INDEX `IXFK_Professor-Subject_Professor` (`idProfessor` ASC)
;

ALTER TABLE `Professor-Subject` 
 ADD INDEX `IXFK_Professor-Subject_Subject` (`idSubject` ASC)
;

ALTER TABLE `Subject` 
 ADD INDEX `IXFK_Subject_Department` (`idDept` ASC)
;

ALTER TABLE `Subject` 
 ADD INDEX `IXFK_Subject_Professor-Subject` (`idSubject` ASC)
;



/* Create Foreign Key Constraints */

ALTER TABLE `Post` 
 ADD CONSTRAINT `FK_Post_Subject`
	FOREIGN KEY (`idSubject`) REFERENCES `Subject` (`idSubject`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `Post` 
 ADD CONSTRAINT `FK_Post_User`
	FOREIGN KEY (`user`) REFERENCES `User` (`user`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `Professor-Subject` 
 ADD CONSTRAINT `FK_Professor-Subject_Professor`
	FOREIGN KEY (`idProfessor`) REFERENCES `Professor` (`idProfessor`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `Professor-Subject` 
 ADD CONSTRAINT `FK_Professor-Subject_Subject`
	FOREIGN KEY (`idSubject`) REFERENCES `Subject` (`idSubject`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `Subject` 
 ADD CONSTRAINT `FK_Subject_Department`
	FOREIGN KEY (`idDept`) REFERENCES `Department` (`idDept`) ON DELETE Restrict ON UPDATE Restrict
;

SET FOREIGN_KEY_CHECKS=1
; 
